name: django_blueprint
services:
  django_db:
    restart: always
    image: postgres:16.3-alpine3.20
    container_name: django_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - django_db:/var/lib/postgresql/data
  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    ports:
      - "8888:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  django_db:
  pgadmin:
